import { preferredLocale } from "./locale";

export const readerLanguages = ["en", "es"] as const;
export type ReaderLanguage = typeof readerLanguages[number];

const messages: Record<ReaderLanguage, Record<string, string>> = {
  en: {
    skip: "Skip to content", language: "Language", saveLanguage: "Use language", evidenceFirst: "Evidence-first news", morningBrief: "Morning brief", homeTitle: "See the reporting behind the story.", homeDescription: "A transparent reader for the reporting behind a story: original links, source counts, and the decision that grouped each report.", topStories: "Top stories", stories: "stories", indexed: "{count} indexed", global: "Global", unitedStates: "United States", unitedKingdom: "United Kingdom", india: "India", noStories: "No stories yet", ingestionNotRun: "Ingestion has not run.", ingestionInstructions: "Add a feed to registry/feeds.json and run pnpm ingest. Deduplicated, source-linked story clusters will appear here.", updateUnavailable: "Update time unavailable", articles: "articles", publications: "publications", offline: "Offline", connectionUnavailable: "Connection unavailable", offlineTitle: "Veritas will not guess at stale evidence.", offlineDescription: "Reconnect to load current reporting, sources, and citations. Saved story IDs remain in your browser, but reports are not cached for offline reading.", tryAgain: "Try again", localBrief: "Local daily brief", followedStories: "Followed stories", followingTitle: "A brief you control, stored on this device.", followingDescription: "Following does not make an account, call a provider, or send your list to Veritas. Optional alerts stay in this browser and only check when you open or refresh this page.", nothingFollowed: "Nothing followed", followToInclude: "Follow a story to include it here.", followedDescription: "Only current public stories are shown. Superseded or no-longer-indexed stories are not retained as a private server record.", updated: "Updated", reports: "reports", followStory: "Follow story", unfollowStory: "Unfollow story", viewBrief: "View local brief", notifications: "Notifications", notificationsDescription: "Optional alerts for changed followed stories. They stay on this device and run only when you open or refresh this brief.", enableNotifications: "Enable local alerts", disableNotifications: "Disable alerts", checkUpdates: "Check for updates", notificationsUnsupported: "This browser does not support notifications.", notificationsDenied: "Notifications are blocked in this browser.", notificationsEnabled: "Local alerts are enabled.", notificationsDisabled: "Local alerts are off.", notificationTitle: "Followed stories updated", notificationBody: "{count} followed stor{suffix} changed since your last check.",
  },
  es: {
    skip: "Saltar al contenido", language: "Idioma", saveLanguage: "Usar idioma", evidenceFirst: "Noticias basadas en evidencia", morningBrief: "Resumen matinal", homeTitle: "Consulta los reportajes detrás de la historia.", homeDescription: "Un lector transparente para los reportajes detrás de una historia: enlaces originales, número de fuentes y la decisión que agrupó cada informe.", topStories: "Historias principales", stories: "historias", indexed: "{count} indexadas", global: "Global", unitedStates: "Estados Unidos", unitedKingdom: "Reino Unido", india: "India", noStories: "Aún no hay historias", ingestionNotRun: "La ingestión no se ha ejecutado.", ingestionInstructions: "Añade una fuente a registry/feeds.json y ejecuta pnpm ingest. Aquí aparecerán agrupaciones de historias deduplicadas y vinculadas a fuentes.", updateUnavailable: "Hora de actualización no disponible", articles: "artículos", publications: "publicaciones", offline: "Sin conexión", connectionUnavailable: "Conexión no disponible", offlineTitle: "Veritas no adivinará con evidencia desactualizada.", offlineDescription: "Vuelve a conectarte para cargar reportajes, fuentes y citas actuales. Los ID de historias guardadas siguen en tu navegador, pero los reportajes no se almacenan para leerlos sin conexión.", tryAgain: "Intentar de nuevo", localBrief: "Resumen diario local", followedStories: "Historias seguidas", followingTitle: "Un resumen que controlas, guardado en este dispositivo.", followingDescription: "Seguir historias no crea una cuenta, no llama a un proveedor ni envía tu lista a Veritas. Las alertas opcionales permanecen en este navegador y solo se revisan al abrir o actualizar esta página.", nothingFollowed: "No sigues historias", followToInclude: "Sigue una historia para incluirla aquí.", followedDescription: "Solo se muestran historias públicas actuales. Las historias sustituidas o ya no indexadas no se conservan como registro privado en el servidor.", updated: "Actualizado", reports: "reportes", followStory: "Seguir historia", unfollowStory: "Dejar de seguir", viewBrief: "Ver resumen local", notifications: "Notificaciones", notificationsDescription: "Alertas opcionales de historias seguidas que han cambiado. Permanecen en este dispositivo y solo se ejecutan al abrir o actualizar este resumen.", enableNotifications: "Activar alertas locales", disableNotifications: "Desactivar alertas", checkUpdates: "Buscar actualizaciones", notificationsUnsupported: "Este navegador no admite notificaciones.", notificationsDenied: "Las notificaciones están bloqueadas en este navegador.", notificationsEnabled: "Las alertas locales están activadas.", notificationsDisabled: "Las alertas locales están desactivadas.", notificationTitle: "Historias seguidas actualizadas", notificationBody: "{count} historias seguidas cambiaron desde tu última consulta.",
  },
};

const labels: Record<ReaderLanguage, Record<string, string>> = {
  en: { developing: "developing", active: "active", settled: "settled", archived: "archived", automatic: "automatic", reviewed: "reviewed", supports: "supports", contradicts: "contradicts", context: "context", unavailable: "unavailable", observed_gap: "observed gap", represented: "represented", direct_reporting: "direct reporting", analysis: "analysis", opinion: "opinion", unknown: "unknown", factual: "factual", statistical: "statistical", causal: "causal", confirmed: "confirmed", well_supported: "well supported", contested: "contested", unverified: "unverified", contradicted: "contradicted" },
  es: { developing: "en desarrollo", active: "activa", settled: "establecida", archived: "archivada", automatic: "automática", reviewed: "revisada", supports: "respalda", contradicts: "contradice", context: "contexto", unavailable: "no disponible", observed_gap: "brecha observada", represented: "representado", direct_reporting: "reportaje directo", analysis: "análisis", opinion: "opinión", unknown: "desconocido", factual: "factual", statistical: "estadística", causal: "causal", confirmed: "confirmado", well_supported: "bien fundamentado", contested: "cuestionado", unverified: "sin verificar", contradicted: "contradicho" },
};

Object.assign(messages.en, { evidenceTrail: "Evidence trail", originalReporting: "Original reporting", trailDescription: "This is a source list, not a credibility verdict. Each entry links to the publisher’s original page and shows why this report was included.", primaryMaterials: "Primary materials & fact checks", reviewedLinks: "{count} reviewed links", noMaterials: "No primary-material or fact-check records have been reviewed for this story.", materialsCaveat: "These are reviewed links to relevant records. Their presence does not by itself confirm every claim in the story.", reportingTimeline: "Reporting timeline", datedReports: "{count} dated reports", timelineCaveat: "This timeline records publication dates, not a reconstruction of real-world events.", diversity: "Reporting diversity", coverage: "Coverage comparison", claimsEvidence: "Claims & evidence", noClaims: "No reviewed claim records have been published. Reports above are the available evidence trail.", corrections: "Corrections", auditRecords: "{count} audit records", storyHistory: "Story history", operations: "{count} operations" });
Object.assign(messages.es, { evidenceTrail: "Rastro de evidencia", originalReporting: "Reportajes originales", trailDescription: "Esta es una lista de fuentes, no un veredicto de credibilidad. Cada entrada enlaza a la página original del medio y muestra por qué se incluyó el reporte.", primaryMaterials: "Materiales primarios y verificaciones", reviewedLinks: "{count} enlaces revisados", noMaterials: "No se han revisado materiales primarios ni verificaciones para esta historia.", materialsCaveat: "Son enlaces revisados a registros relevantes. Su presencia no confirma por sí sola cada afirmación de la historia.", reportingTimeline: "Cronología de reportajes", datedReports: "{count} reportes fechados", timelineCaveat: "Esta cronología registra fechas de publicación, no reconstruye acontecimientos del mundo real.", diversity: "Diversidad de reportajes", coverage: "Comparación de cobertura", claimsEvidence: "Afirmaciones y evidencia", noClaims: "No se han publicado afirmaciones revisadas. Los reportajes anteriores son el rastro de evidencia disponible.", corrections: "Correcciones", auditRecords: "{count} registros de auditoría", storyHistory: "Historial de la historia", operations: "{count} operaciones" });

export function readerLocale(preference: string | undefined, acceptLanguage: string | null): string {
  return readerLanguages.includes(preference as ReaderLanguage) ? preference! : preferredLocale(acceptLanguage);
}

export function readerLanguage(locale: string): ReaderLanguage {
  try {
    const language = new Intl.Locale(locale).language;
    return readerLanguages.includes(language as ReaderLanguage) ? language as ReaderLanguage : "en";
  } catch {
    return "en";
  }
}

export function t(language: ReaderLanguage, key: string, values: Record<string, string | number> = {}) {
  return (messages[language][key] ?? messages.en[key] ?? key).replace(/\{(\w+)\}/g, (_match, name: string) => String(values[name] ?? ""));
}

export function readerLabel(language: ReaderLanguage, value: string) {
  return labels[language][value] ?? labels.en[value] ?? value.replaceAll("_", " ");
}
