import Link from "next/link";
import { notFound } from "next/navigation";

import { claimStatuses } from "@/lib/claims";
import { dashboardIsConfigured, isOwner } from "@/lib/owner-session";
import { getStory } from "@/lib/stories";
import { materialTypes } from "@/lib/primary-materials";
import { coverageForms, topics } from "@/lib/coverage";
import { addClaim, addPrimaryEvidence, addReportingChain, attachPrimaryMaterial, correctEvidence, mergeStory, publishSummary, recomputeStoryData, setCoverage, setTopic, splitStory } from "./actions";

const label = (value: string) => value.replaceAll("_", " ");

export default async function ReviewStoryPage({ params }: { params: Promise<{ id: string }> }) {
  const id = (await params).id;
  if (!dashboardIsConfigured() || !(await isOwner())) notFound();
  const story = getStory(id);
  if (!story) notFound();
  return <main id="main-content" className="shell">
    <header className="masthead"><Link className="wordmark" href={`/stories/${id}`}>VERITAS</Link><p>Operator review</p></header>
    <section className="brief"><p className="eyebrow">Grounded evidence</p><h1>Add a claim with a source note.</h1><p className="lede">This does not verify the claim. It records a reviewable statement and the report that supports, contradicts, or contextualizes it.</p></section>
    <form action={addClaim} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Claim<input name="text" required minLength={8} maxLength={500} autoComplete="off" /></label><label>Status<select name="status" defaultValue="unverified">{claimStatuses.map((status) => <option key={status} value={status}>{label(status)}</option>)}</select></label><label>Evidence report<select name="articleId">{story.articles.map((article) => <option key={article.id} value={article.id}>{article.sourceName} — {article.title}</option>)}</select></label><label>How this report relates<select name="stance" defaultValue="context"><option value="supports">Supports</option><option value="contradicts">Contradicts</option><option value="context">Provides context</option></select></label><label>Attributed evidence note<input name="note" required minLength={8} maxLength={500} autoComplete="off" /></label><button type="submit">Publish evidence record</button></form>
    <section className="operator-section"><h2>Publish reviewed summary</h2><form action={publishSummary} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Evidence report<select name="articleId">{story.articles.map((article) => <option key={article.id} value={article.id}>{article.sourceName} — {article.title}</option>)}</select></label><label>Summary<input name="text" required minLength={20} maxLength={1000} autoComplete="off" defaultValue={story.summaryRecord?.text ?? ""}/></label><button type="submit">Publish reviewed summary</button></form></section>
    <section className="operator-section"><h2>Topic and coverage form</h2><p>These records describe observable form, not ideology or accuracy.</p><form action={setTopic} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Topic<select name="topic" defaultValue={story.topic ?? "other"}>{topics.map((topic)=><option key={topic} value={topic}>{label(topic)}</option>)}</select></label><button type="submit">Publish topic</button></form><form action={setCoverage} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Report<select name="articleId">{story.articles.map((article)=><option key={article.id} value={article.id}>{article.sourceName} — {article.title}</option>)}</select></label><label>Coverage form<select name="coverageForm">{coverageForms.map((form)=><option key={form} value={form}>{label(form)}</option>)}</select></label><label>Observed focus<input name="focusNote" required minLength={8} maxLength={500} /></label><button type="submit">Publish coverage record</button></form></section>
    <section className="operator-section"><h2>Record primary material or fact check</h2><p>Links are evidence records, not an automatic verification verdict.</p><form action={addPrimaryEvidence} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Title<input name="title" required minLength={3} maxLength={300} autoComplete="off" /></label><label>Material type<select name="materialType">{materialTypes.map((type) => <option key={type} value={type}>{label(type)}</option>)}</select></label><label>Public HTTPS link<input name="url" type="url" required maxLength={2048} autoComplete="off" placeholder="https://…" /></label><label>Why it is relevant<input name="relevanceNote" required minLength={8} maxLength={500} autoComplete="off" /></label><label>Publication time, ISO 8601 UTC (optional)<input name="publishedAt" type="text" inputMode="text" autoComplete="off" placeholder="2026-08-18T12:00:00Z" /></label><button type="submit">Publish material record</button></form></section>
    {story.claims.length > 0 && story.primaryMaterials.length > 0 && <section className="operator-section"><h2>Attach primary material to a claim</h2><form action={attachPrimaryMaterial} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Claim<select name="claimId">{story.claims.map((claim)=><option key={claim.id} value={claim.id}>{claim.text}</option>)}</select></label><label>Primary material<select name="primaryMaterialId">{story.primaryMaterials.map((material)=><option key={material.id} value={material.id}>{material.title}</option>)}</select></label><label>Relationship<select name="stance"><option value="supports">Supports</option><option value="contradicts">Contradicts</option><option value="context">Provides context</option></select></label><label>Evidence note<input name="note" required minLength={8} maxLength={500} /></label><button type="submit">Attach primary evidence</button></form></section>}
    {(story.claims.length > 0 || story.primaryMaterials.length > 0) && <section className="operator-section"><h2>Correct evidence and recompute</h2><p>Corrections append a public audit record. They do not rewrite the original report, claim, or material.</p><form action={correctEvidence} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Evidence record<select name="target"><optgroup label="Claims">{story.claims.map((claim)=><option key={claim.id} value={`claim:${claim.id}`}>{claim.text}</option>)}</optgroup><optgroup label="Primary materials">{story.primaryMaterials.map((material)=><option key={material.id} value={`primary_material:${material.id}`}>{material.title}</option>)}</optgroup></select></label><label>Correction note<input name="note" required minLength={8} maxLength={1000} autoComplete="off" /></label><button type="submit">Publish correction and recompute</button></form><form action={recomputeStoryData} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Recompute reason<input name="reason" required minLength={8} maxLength={500} autoComplete="off" placeholder="Refresh derived report count after review" /></label><button type="submit">Recompute derived data</button></form></section>}
    <section className="operator-section"><h2>Split a misclustered report</h2><form action={splitStory} className="credential-form"><input type="hidden" name="sourceStoryId" value={id}/><label>Report<select name="articleId">{story.articles.map((article) => <option key={article.id} value={article.id}>{article.sourceName} — {article.title}</option>)}</select></label><label>New story headline<input name="headline" required minLength={8} maxLength={300} autoComplete="off" /></label><label>Reason<input name="reason" required minLength={8} maxLength={500} autoComplete="off" /></label><button type="submit">Split into new story</button></form></section>
    <section className="operator-section"><h2>Merge this story into another</h2><form action={mergeStory} className="credential-form"><input type="hidden" name="sourceStoryId" value={id}/><label>Target story ID<input name="targetStoryId" required pattern="[0-9a-fA-F-]{36}" autoComplete="off" /></label><label>Reason<input name="reason" required minLength={8} maxLength={500} autoComplete="off" /></label><button type="submit">Merge stories</button></form></section>
    <section className="operator-section"><h2>Record reporting chain</h2><form action={addReportingChain} className="credential-form"><input type="hidden" name="storyId" value={id}/><label>Evidence report<select name="articleId">{story.articles.map((article) => <option key={article.id} value={article.id}>{article.sourceName} — {article.title}</option>)}</select></label><label>Chain label<input name="label" required minLength={3} maxLength={160} autoComplete="off" placeholder="Named wire service…" /></label><label>Evidence basis<input name="basis" required minLength={8} maxLength={500} autoComplete="off" /></label><label>Confidence (0–1)<input name="confidence" type="number" min="0" max="1" step="0.1" defaultValue="0.5" required/></label><button type="submit">Publish reporting chain</button></form></section>
  </main>;
}
