import Link from "next/link";
import { listStoredCredentials, providers } from "@/lib/credentials";
import { dashboardIsConfigured, isOwner } from "@/lib/owner-session";
import { deleteProvider, login, logout, saveProvider } from "./actions";

export const dynamic = "force-dynamic";
export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const configured = dashboardIsConfigured(); const owner = await isOwner(); const error = (await searchParams).error;
  if (!configured) return <main className="shell"><Link className="wordmark" href="/">VERITAS</Link><section className="brief"><p className="eyebrow">Owner settings</p><h1>Dashboard credentials are disabled.</h1><p className="lede">Set a 32-byte base64 <code>VERITAS_ENCRYPTION_KEY</code> and a 16+ character <code>VERITAS_ADMIN_PASSWORD</code> in <code>.env</code>, then restart. Environment provider keys work without this dashboard.</p></section></main>;
  if (!owner) return <main className="shell"><Link className="wordmark" href="/">VERITAS</Link><section className="brief"><p className="eyebrow">Owner settings</p><h1>Unlock credentials.</h1><form action={login} className="credential-form"><label htmlFor="password">Owner password</label><input id="password" name="password" type="password" autoComplete="current-password" required minLength={16}/>{error && <p role="alert">Password was not accepted.</p>}<button type="submit">Unlock settings</button></form></section></main>;
  const credentials = listStoredCredentials();
  return <main className="shell"><header className="masthead"><Link className="wordmark" href="/">VERITAS</Link><form action={logout}><button className="quiet" type="submit">Lock settings</button></form></header><section className="brief"><p className="eyebrow">Owner settings</p><h1>Provider credentials</h1><p className="lede">Saved keys are encrypted at rest and only their final four characters are shown.</p></section><section><div className="section-heading"><h2>Saved credentials</h2><span>{credentials.length} configured</span></div>{credentials.map((item) => <div className="story" key={item.provider}><h3>{item.provider}</h3><p className="metrics">{item.maskedSuffix}{item.model ? ` · ${item.model}` : ""}</p><form action={deleteProvider}><input type="hidden" name="provider" value={item.provider}/><button className="quiet" type="submit">Delete</button></form></div>)}</section><section className="settings-add"><h2>Add or replace a credential</h2><form action={saveProvider} className="credential-form"><label>Provider<select name="provider">{providers.map((provider) => <option key={provider}>{provider}</option>)}</select></label><label>API key<input name="secret" type="password" autoComplete="off" required /></label><label>Base URL (OpenAI-compatible only)<input name="baseUrl" type="url" placeholder="https://api.openai.com/v1" /></label><label>Model (optional)<input name="model" /></label><button type="submit">Save encrypted credential</button></form></section></main>;
}
