import Link from "next/link";

import { listStoredCredentials, providers } from "@/lib/credentials";
import { dashboardIsConfigured, isOwner } from "@/lib/owner-session";
import { login, logout, saveProvider, testProvider } from "./actions";
import { DeleteCredentialForm } from "./delete-credential-form";

export const dynamic = "force-dynamic";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; notice?: string }> }) {
  const configured = dashboardIsConfigured(); const owner = await isOwner(); const { error, notice } = await searchParams;
  if (!configured) return <main id="main-content" className="shell"><Link className="wordmark" href="/">VERITAS</Link><section className="brief"><p className="eyebrow">Owner settings</p><h1>Dashboard credentials are disabled.</h1><p className="lede">Set a 32-byte base64 <code>VERITAS_ENCRYPTION_KEY</code> and a 16+ character <code>VERITAS_ADMIN_PASSWORD</code> in <code>.env</code>, then restart. Environment provider keys work without this dashboard.</p></section></main>;
  if (!owner) return <main id="main-content" className="shell"><Link className="wordmark" href="/">VERITAS</Link><section className="brief"><p className="eyebrow">Owner settings</p><h1>Unlock credentials.</h1><form action={login} className="credential-form"><label htmlFor="password">Owner password</label><input id="password" name="password" type="password" autoComplete="current-password" required minLength={16}/>{error && <p role="alert">Password was not accepted. Check the password and try again.</p>}<button type="submit">Unlock settings</button></form></section></main>;
  const credentials = listStoredCredentials();
  const connectionNotice = notice === "verified" ? "OpenAI-compatible connection verified." : notice === "failed" ? "Connection could not be verified. Check the key and endpoint." : notice === "unsupported" ? "Connection tests are available for OpenAI-compatible credentials only." : null;
  return <main id="main-content" className="shell"><header className="masthead"><Link className="wordmark" href="/">VERITAS</Link><form action={logout}><button className="quiet" type="submit">Lock settings</button></form></header><section className="brief"><p className="eyebrow">Owner settings</p><h1>Provider credentials</h1><p className="lede">Saved keys are encrypted at rest and only their final four characters are shown.</p>{connectionNotice && <p role="status">{connectionNotice}</p>}</section><section><div className="section-heading"><h2>Saved credentials</h2><span>{credentials.length} configured</span></div>{credentials.map((item) => <div className="story" key={item.provider}><h3>{item.provider}</h3><p className="metrics">{item.maskedSuffix}{item.model ? ` · ${item.model}` : ""}</p>{item.provider === "openai" && <form action={testProvider}><input type="hidden" name="provider" value="openai"/><button className="quiet" type="submit">Test connection</button></form>}<DeleteCredentialForm provider={item.provider}/></div>)}</section><section className="settings-add"><h2>Add or replace a credential</h2><form action={saveProvider} className="credential-form"><label>Provider<select name="provider" autoComplete="off">{providers.map((provider) => <option key={provider}>{provider}</option>)}</select></label><label>API key<input name="secret" type="password" autoComplete="off" required /></label><label>Base URL (OpenAI-compatible only)<input name="baseUrl" type="url" autoComplete="off" placeholder="https://api.openai.com/v1…" /></label><label>Model (optional)<input name="model" autoComplete="off" /></label><button type="submit">Save encrypted credential</button></form></section></main>;
}
